root = "."
tmp_dir = "tmp"

[build]
  # TARGET będzie przekazywany z Taskfile jako zmienna środowiskowa
  cmd = "go build -o ./tmp/app ./cmd/${TARGET}"
  bin = "tmp/app"
  full_bin = "./tmp/app"
  include_ext = ["go", "tpl", "tmpl", "html", "yaml"]
  exclude_dir = ["bin", "tmp", "vendor"]
  poll = true   # <-- ważne w Dockerze

[log]
  time = true
